language: php
php: 
  - 7.2
  - 7.3 
services:
  - mysql

before_script:
   - composer install
   - composer dump-autoload

script: vendor/bin/phpunit --configuration=phpunit.xml tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f /tmp/coverage.xml ]; then php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml; fi;
