language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
script: phpunit --configuration=.phpunit.xml tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml; fi;
