language: php
php: 
  - 7.3 
  - 7.4
  - 8.0
services:
  - mysql

before_script:
   - LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
   
   # To make sure everything works properly, we need to load ffmpeg, a modern version
   # of GD (that includes imagewebp functions) nad ffmpeg
   - apt-get update
   - apt-get install ffmpeg
   - apt-get install -y apt-utils php"$PHP_VERSION"-gd
   - printf "\n" | pecl install imagick
   
   # Initialize the composer stuff.
   - composer install
   - composer dump-autoload

script: vendor/bin/phpunit --configuration=phpunit.xml tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f /tmp/coverage.xml ]; then php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml; fi;
