language: php
dist: focal
php: 
  - 7.4
  - 8.0
services:
  - mysql

before_script:
  - LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
  
  - sudo apt-get update
  - sudo apt-get install -y php$(phpenv version-name)-cli php$(phpenv version-name)-xml php$(phpenv version-name)-curl 
  - sudo apt-get install -y php$(phpenv version-name)-zip php$(phpenv version-name)-mbstring php$(phpenv version-name)-mysql 
  - sudo apt-get install -y php$(phpenv version-name)-xdebug
  
  # In September 2021, the Let's encrypt root authority certificate expired, this has
  # caused git to reject our certificates on phabricator.magic3w.com. Updating the certs
  # should do the trick here.
  # See: https://stackoverflow.com/questions/35821245/github-server-certificate-verification-failed
  - sudo apt-get install --reinstall ca-certificates && sudo update-ca-certificates
  
  - php -v
  - rm -f /home/travis/.phpenv/shims/php
  - ln -s /usr/bin/php /home/travis/.phpenv/shims/php
  - which php
  
  # Initialize the composer stuff.
  - composer install
  - composer dump-autoload

script: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration=phpunit.xml tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f /tmp/coverage.xml ]; then php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml; fi;
